### PR TITLE
[TRI-31011] JIRA issue collector with feedback button

### PR DESCRIPTION
**Pull request by shilpasivanesan-tri**

### CODE REVIEW

**Comment by shilpasivanesan-tri** [comment]
Screenshot 2024-01-22 at 8 58 00 PM
Screenshot 2024-01-22 at 8 58 11 PM

**Comment by shilpasivanesan-tri** [comment]
@mehradans , Noticed couple of issues

https://github.com/TRI-AMDD/piro/assets/153004701/b8b2ec2a-ada1-4ee2-bac5-e2444e8b7011


The jira collector template looks different to what is attached in the ticket
Also after submitting the issue , I dont see it created under the epic
With the issue collector form , the fields are not validated eg:email field accepts value without @

**Review by mike-puzon-tri — CHANGES_REQUESTED** [review]
Please run lint-fix to fix linting issues

**Comment by mike-puzon-tri** [comment]
Looks like there are some conflicts

**Review by mike-puzon-tri — APPROVED** [review]

**Review by Pradeepvarma333 — APPROVED** [review]

**Review by Pradeepvarma333 — APPROVED** [review]

**Pull request merged**
