### PR TITLE
additional changes for prelogin page

### PR DESCRIPTION
**Pull request by Pradeepvarma333**
additional changes for prelogin page

### CODE REVIEW

**Review by mike-puzon-tri — CHANGES_REQUESTED** [review]
Please import Gellix Medium Bold and use that for the buttons

**Comment by mike-puzon-tri** [comment]
Also please address errors in Web Testing and Linting.

**Comment by shilpasivanesan-tri** [comment]
At Footer, fonts colour looks different.
With pre login its only copyright , but I just checked the footer in other pages , they seems to be different. could you please check ?

**Comment by Pradeepvarma333** [comment]
> At Footer, fonts colour/ size looks different. With pre login its only copyright , but I just checked the footer in other pages , they seems to be different. could you please check ?

Hi Shilpa , used Gellix medium for both header and footer, and font weight and color is also same as per figma.

**Review by mike-puzon-tri — APPROVED** [review]

**Pull request merged**
