### PR TITLE
Convert dash to react and api

### PR DESCRIPTION
**Pull request by ChrisFajardo-TRI**
@MuratAykol-TRI @JosephMontoya-TRI 

Here is a PR for converting Dash to React + FastAPI that I worked on this sprint with @michaelpuzon 
We'll schedule a meeting to demo

Dash app moved to web/dash folder
- Made sure docker still works/optimized the docker file
- moved dependencies from setup.py to requirements.txt within web/dash since we'll have different web options. setup.py will be mainly for the piro module

FastAPI app in web/backend
- It's a lightweight and simple to use framework similar to Flask but modern and better in many ways. (but easy to change back to Flask if desired)
- It's set up to be able to serve the React app to mimic Dash and can run in a single docker container.
 
React app in web/frontend
- inputs are validated before submission
- display error messages
- TRI styling/components/logos

### CODE REVIEW

**Comment by ChrisFajardo-TRI** [comment]
Also @MuratAykol-TRI I made one API change.

"add_element" was used in the code both a string and list of string. so I think there's a bug somewhere. I assumed to be more flexible and changed it to "add_elements" which is list of string everywhere.
Let me know if that's ok or you want me to change it back.

**Comment by MuratAykol-TRI** [comment]
@ChrisFajardo-TRI This is fantastic in my view, having seen also the demo. But unless this is blocking another task, might be good to wait for @JosephMontoya-TRI to find time to take a look as well.

**Comment by ChrisFajardo-TRI** [comment]
good thing it wasn't merged yet because I did find a bug in the dock. 

tests are failing in this and other PRs because of a bug, which I fixed as a part of this PR but I don't know if I want to fix it everywhere. https://github.com/TRI-AMDD/piro/pull/27
will just wait until all the PRs get merged

**Comment by ChrisFajardo-TRI** [comment]
so actually, we're starting to get new work streams based on this PR. is it ok if we merge this? @JosephMontoya-TRI @MuratAykol-TRI 

the old Dash stuff should still work if we need to fall back.

**Comment by JosephMontoya-TRI** [comment]
Let me issue a quick pr to try to deal with the pymatgen update issue, then we'll merge

**Pull request merged**
